spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always # Habilitar o log colorido
server:
  port: 8080
mybatis:
  type-aliases-package: com.example.produtomybatis.model
  mapper-locations: classpath*:**/mappers/*Mapper.xml
---
# Configurações de Desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
      path: /console
---
# Configurações de Produção
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/produtodb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  h2:
    console:
      enabled: true
      path: /console